plugins {
    id 'java'
    id 'application'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.+'
    testImplementation 'org.hamcrest:hamcrest:2.2'
    testImplementation 'io.rest-assured:rest-assured:6.+'
}

